import React, { useState } from 'react';
import { Globe, Briefcase, BarChart2, Loader2, Percent, Sparkles } from 'lucide-react';
import IndexCard from './IndexCard';
import { GeminiService } from '../services/geminiService';
import { IndexInfo, LoadingStatus, Source } from '../types';
import { useSettings } from '../contexts/LanguageContext';

const INDICES: IndexInfo[] = [
  { name: 'S&P 500', description: 'SPX', queryName: 'S&P 500 Index' },
  { name: 'Dow Jones', description: 'DJI', queryName: 'Dow Jones Industrial Average Index' },
  { name: 'Nasdaq', description: 'IXIC', queryName: 'Nasdaq Composite Index' },
];

const MacroSection: React.FC = () => {
  const { t, settings } = useSettings();
  const language = settings.language;
  const [viewStatus, setViewStatus] = useState<LoadingStatus>(LoadingStatus.IDLE);
  const [marketView, setMarketView] = useState<string>('');
  const [sources, setSources] = useState<Source[]>([]);

  const fetchView = async () => {
    if (viewStatus === LoadingStatus.LOADING) return;
    setViewStatus(LoadingStatus.LOADING);
    setMarketView(''); // Clear previous content to avoid dupes visually
    
    try {
      const result = await GeminiService.fetchOverallMarketView(language);
      setMarketView(result.text);
      setSources(result.sources);
      setViewStatus(LoadingStatus.SUCCESS);
    } catch (e) {
      setMarketView('Error fetching macro analysis.');
      setViewStatus(LoadingStatus.ERROR);
    }
  };

  const formatMarketView = (text: string) => {
    // Basic cleaning and markdown support
    if (!text) return null;
    
    // Split by newlines, filter empty lines, and remove adjacent duplicates to prevent "stuttering"
    const lines = text.split('\n').filter(line => line.trim() !== '');
    const uniqueLines = lines.filter((line, i) => i === 0 || line !== lines[i-1]);

    return uniqueLines.map((line, i) => {
       // Parse bold syntax **text**
       const parts = line.split(/(\*\*.*?\*\*)/g);
       
       // Check if line is a header (starts with # or ##)
       const isHeader = line.trim().startsWith('#');
       const cleanLine = isHeader ? line.replace(/^#+\s*/, '') : line;
       const className = isHeader 
           ? "mb-3 mt-4 text-base font-bold text-sky-800 dark:text-sky-300 border-b border-sky-100 dark:border-slate-700 pb-1" 
           : "mb-2 text-sm text-slate-700 dark:text-slate-300 leading-relaxed";

       return (
         <p key={i} className={className}>
            {parts.map((part, j) => {
                if (part.startsWith('**') && part.endsWith('**')) {
                    return <strong key={j} className="font-semibold text-slate-900 dark:text-slate-100">{part.slice(2, -2)}</strong>;
                }
                if (isHeader) return part.replace(/^#+\s*/, '');
                return part;
            })}
         </p>
       );
    });
  };

  return (
    <section className="bg-sky-50 dark:bg-sky-900/20 p-6 rounded-xl shadow-inner border border-sky-200 dark:border-sky-800 transition-colors">
      <h2 className="text-2xl font-bold text-sky-800 dark:text-sky-400 mb-4 flex items-center border-b pb-2 border-sky-300 dark:border-sky-700">
        <Globe className="w-5 h-5 mr-2" />
        {t('macro.title')}
      </h2>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6 mb-8">
        <div className="lg:col-span-3 bg-white dark:bg-slate-800 p-6 rounded-lg shadow-md border border-sky-100 dark:border-slate-700 relative transition-colors min-h-[200px] flex flex-col">
          <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-sky-400 to-teal-400 rounded-t-lg"></div>
          <h3 className="text-base font-semibold text-sky-700 dark:text-sky-300 mb-4 flex items-center">
            <Briefcase className="w-4 h-4 mr-1 text-teal-500" /> 
            AI Strategist View
            {viewStatus === LoadingStatus.SUCCESS && <span className="ml-auto text-xs text-slate-400 font-normal">Generated by Gemini</span>}
          </h3>
          <div className="text-sm text-slate-700 dark:text-slate-300 flex-grow">
            {viewStatus === LoadingStatus.LOADING ? (
                 <div className="flex flex-col items-center justify-center h-40 text-sky-600 dark:text-sky-400 animate-pulse">
                     <Sparkles className="w-8 h-8 mb-3 animate-spin" />
                     <p className="text-sm font-medium">Analyzing Global Markets...</p>
                 </div>
            ) : marketView ? (
                 formatMarketView(marketView) 
            ) : (
                 <div className="py-12 text-center text-slate-400 dark:text-slate-500 flex flex-col items-center">
                     <BarChart2 className="w-12 h-12 mb-2 opacity-20" />
                     <p>Click "Generate Report" to analyze current market conditions.</p>
                 </div>
            )}
          </div>
          {sources.length > 0 && (
             <div className="mt-4 pt-3 border-t border-slate-100 dark:border-slate-700">
                <p className="text-xs text-slate-400 mb-1">Sources:</p>
                <div className="flex flex-wrap gap-2">
                    {sources.map((s, idx) => (
                        <a key={idx} href={s.uri} target="_blank" rel="noopener noreferrer" className="text-xs bg-slate-100 dark:bg-slate-700 text-sky-600 dark:text-sky-400 px-2 py-1 rounded hover:bg-sky-50 dark:hover:bg-slate-600 truncate max-w-[200px] transition-colors">
                            {s.title}
                        </a>
                    ))}
                </div>
             </div>
          )}
        </div>

        <div className="lg:col-span-1 flex flex-col justify-start space-y-4">
          <button
            onClick={fetchView}
            disabled={viewStatus === LoadingStatus.LOADING}
            className="bg-sky-600 hover:bg-sky-700 text-white font-bold py-4 px-6 rounded-xl shadow-lg w-full flex flex-col items-center disabled:opacity-75 transition-all active:scale-95 group"
          >
            {viewStatus === LoadingStatus.LOADING ? <Loader2 className="w-8 h-8 mb-2 animate-spin" /> : <BarChart2 className="w-8 h-8 mb-2 group-hover:scale-110 transition-transform" />}
            <span>{viewStatus === LoadingStatus.LOADING ? 'Analyzing...' : 'Generate Report'}</span>
          </button>
          
          <div className="bg-sky-100 dark:bg-sky-900/30 p-4 rounded-lg border border-sky-200 dark:border-sky-800/50">
             <h4 className="text-xs font-bold text-sky-800 dark:text-sky-300 uppercase tracking-wider mb-2">Coverage</h4>
             <ul className="text-xs text-sky-700 dark:text-sky-400 space-y-1">
                 <li>• US Treasury Yields</li>
                 <li>• VIX Volatility Index</li>
                 <li>• Inflation Data</li>
                 <li>• Federal Reserve Policy</li>
                 <li>• Geopolitical Risks</li>
             </ul>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
        {INDICES.map((idx) => <IndexCard key={idx.name} info={idx} />)}
      </div>
    </section>
  );
};

export default MacroSection;